from .branch_routes import branch_bp
from .customer_routes import customer_bp
from .delivery_routes import delivery_bp
from .employee_routes import employee_bp
from .kpopgroup_routes import kpopgroup_bp
from .order_routes import order_bp
from .product_routes import product_bp
from .shipping_routes import shipping_bp
from .warehouse_routes import warehouse_bp
