from routes.branch_routes import branch_bp
from routes.customer_routes import customer_bp
from routes.delivery_routes import delivery_bp
from routes.employee_routes import employee_bp
from routes.kpopgroup_routes import kpopgroup_bp
from routes.order_routes import order_bp
from routes.product_routes import product_bp
from routes.shipping_routes import shipping_bp
from routes.warehouse_routes import warehouse_bp
